spring:

  jpa:
    show-sql: true

    hibernate:
      ddl-auto: update

# flyway is configured in FlywayConfiguration class
  flyway:
    enabled: false

  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: usr
    password: passwd

  mail:
    host: localhost
    port: 1025
    username: usr
    password: psswd
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

app:
  imagesPath: src/main/resources/static/images/