spring:

  jpa:
    show-sql: true

    hibernate:
      ddl-auto: update

# flyway is configured in FlywayConfiguration class
  flyway:
    enabled: false

  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: usr
    password: passwd

app:
  imagesPath: src/main/resources/static/images/